// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_pedigree_placeholder
int cpp_pedigree_placeholder(int x);
RcppExport SEXP _mispitools_cpp_pedigree_placeholder(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pedigree_placeholder(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_marker_placeholder
int cpp_marker_placeholder(int x);
RcppExport SEXP _mispitools_cpp_marker_placeholder(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_marker_placeholder(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_mutation_models_placeholder
int cpp_mutation_models_placeholder(int x);
RcppExport SEXP _mispitools_cpp_mutation_models_placeholder(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_mutation_models_placeholder(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cpt_engine_placeholder
int cpp_cpt_engine_placeholder(int x);
RcppExport SEXP _mispitools_cpp_cpt_engine_placeholder(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cpt_engine_placeholder(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_kl_engine_placeholder
int cpp_kl_engine_placeholder(int x);
RcppExport SEXP _mispitools_cpp_kl_engine_placeholder(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_kl_engine_placeholder(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lr_dist_placeholder
int cpp_lr_dist_placeholder(int x);
RcppExport SEXP _mispitools_cpp_lr_dist_placeholder(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lr_dist_placeholder(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_nongenetic_lr_placeholder
int cpp_nongenetic_lr_placeholder(int x);
RcppExport SEXP _mispitools_cpp_nongenetic_lr_placeholder(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_nongenetic_lr_placeholder(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_evidence_combine_placeholder
int cpp_evidence_combine_placeholder(int x);
RcppExport SEXP _mispitools_cpp_evidence_combine_placeholder(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_evidence_combine_placeholder(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_concentration_placeholder
int cpp_concentration_placeholder(int x);
RcppExport SEXP _mispitools_cpp_concentration_placeholder(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_concentration_placeholder(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_decision_placeholder
int cpp_decision_placeholder(int x);
RcppExport SEXP _mispitools_cpp_decision_placeholder(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_decision_placeholder(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_linkage_placeholder
int cpp_linkage_placeholder(int x);
RcppExport SEXP _mispitools_cpp_linkage_placeholder(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_linkage_placeholder(x));
    return rcpp_result_gen;
END_RCPP
}
// cpt_marker_joint_cpp
Rcpp::List cpt_marker_joint_cpp(Rcpp::IntegerVector father, Rcpp::IntegerVector mother, int poi, Rcpp::NumericVector freqs, int mutation_kind, double mutation_rate, double mutation_range, double mutation_rate2, double mutation_bias, Rcpp::NumericVector numeric_labels, Rcpp::IntegerVector relevant);
RcppExport SEXP _mispitools_cpt_marker_joint_cpp(SEXP fatherSEXP, SEXP motherSEXP, SEXP poiSEXP, SEXP freqsSEXP, SEXP mutation_kindSEXP, SEXP mutation_rateSEXP, SEXP mutation_rangeSEXP, SEXP mutation_rate2SEXP, SEXP mutation_biasSEXP, SEXP numeric_labelsSEXP, SEXP relevantSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type father(fatherSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type mother(motherSEXP);
    Rcpp::traits::input_parameter< int >::type poi(poiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type freqs(freqsSEXP);
    Rcpp::traits::input_parameter< int >::type mutation_kind(mutation_kindSEXP);
    Rcpp::traits::input_parameter< double >::type mutation_rate(mutation_rateSEXP);
    Rcpp::traits::input_parameter< double >::type mutation_range(mutation_rangeSEXP);
    Rcpp::traits::input_parameter< double >::type mutation_rate2(mutation_rate2SEXP);
    Rcpp::traits::input_parameter< double >::type mutation_bias(mutation_biasSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type numeric_labels(numeric_labelsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type relevant(relevantSEXP);
    rcpp_result_gen = Rcpp::wrap(cpt_marker_joint_cpp(father, mother, poi, freqs, mutation_kind, mutation_rate, mutation_range, mutation_rate2, mutation_bias, numeric_labels, relevant));
    return rcpp_result_gen;
END_RCPP
}
// cpp_per_marker_kl
Rcpp::List cpp_per_marker_kl(Rcpp::NumericVector p_h1, Rcpp::NumericVector p_h2);
RcppExport SEXP _mispitools_cpp_per_marker_kl(SEXP p_h1SEXP, SEXP p_h2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p_h1(p_h1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p_h2(p_h2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_per_marker_kl(p_h1, p_h2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_per_marker_lr_dist
Rcpp::List cpp_per_marker_lr_dist(Rcpp::NumericVector p_h1, Rcpp::NumericVector p_h2, bool aggregate);
RcppExport SEXP _mispitools_cpp_per_marker_lr_dist(SEXP p_h1SEXP, SEXP p_h2SEXP, SEXP aggregateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p_h1(p_h1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p_h2(p_h2SEXP);
    Rcpp::traits::input_parameter< bool >::type aggregate(aggregateSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_per_marker_lr_dist(p_h1, p_h2, aggregate));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lr_dist_compose
Rcpp::List cpp_lr_dist_compose(Rcpp::List dists, std::string method, double merge_tol, int grid_points);
RcppExport SEXP _mispitools_cpp_lr_dist_compose(SEXP distsSEXP, SEXP methodSEXP, SEXP merge_tolSEXP, SEXP grid_pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dists(distsSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< double >::type merge_tol(merge_tolSEXP);
    Rcpp::traits::input_parameter< int >::type grid_points(grid_pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lr_dist_compose(dists, method, merge_tol, grid_points));
    return rcpp_result_gen;
END_RCPP
}
// cpp_evidence_combine
Rcpp::List cpp_evidence_combine(Rcpp::List dists, std::string mode, Rcpp::Nullable<Rcpp::List> transition);
RcppExport SEXP _mispitools_cpp_evidence_combine(SEXP distsSEXP, SEXP modeSEXP, SEXP transitionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type dists(distsSEXP);
    Rcpp::traits::input_parameter< std::string >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type transition(transitionSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_evidence_combine(dists, mode, transition));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lr_dist_summary
Rcpp::List cpp_lr_dist_summary(Rcpp::NumericVector log10_lr, Rcpp::NumericVector p_h1, Rcpp::NumericVector p_h2);
RcppExport SEXP _mispitools_cpp_lr_dist_summary(SEXP log10_lrSEXP, SEXP p_h1SEXP, SEXP p_h2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type log10_lr(log10_lrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p_h1(p_h1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p_h2(p_h2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lr_dist_summary(log10_lr, p_h1, p_h2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lr_dist_quantile
Rcpp::NumericVector cpp_lr_dist_quantile(Rcpp::NumericVector log10_lr, Rcpp::NumericVector p_h1, Rcpp::NumericVector p_h2, Rcpp::NumericVector probs, bool under_h1);
RcppExport SEXP _mispitools_cpp_lr_dist_quantile(SEXP log10_lrSEXP, SEXP p_h1SEXP, SEXP p_h2SEXP, SEXP probsSEXP, SEXP under_h1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type log10_lr(log10_lrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p_h1(p_h1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p_h2(p_h2SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< bool >::type under_h1(under_h1SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lr_dist_quantile(log10_lr, p_h1, p_h2, probs, under_h1));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lr_dist_decision_rates
Rcpp::List cpp_lr_dist_decision_rates(Rcpp::NumericVector log10_lr, Rcpp::NumericVector p_h1, Rcpp::NumericVector p_h2, double threshold);
RcppExport SEXP _mispitools_cpp_lr_dist_decision_rates(SEXP log10_lrSEXP, SEXP p_h1SEXP, SEXP p_h2SEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type log10_lr(log10_lrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p_h1(p_h1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p_h2(p_h2SEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lr_dist_decision_rates(log10_lr, p_h1, p_h2, threshold));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lr_dist_roc
Rcpp::List cpp_lr_dist_roc(Rcpp::NumericVector log10_lr, Rcpp::NumericVector p_h1, Rcpp::NumericVector p_h2);
RcppExport SEXP _mispitools_cpp_lr_dist_roc(SEXP log10_lrSEXP, SEXP p_h1SEXP, SEXP p_h2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type log10_lr(log10_lrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p_h1(p_h1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p_h2(p_h2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lr_dist_roc(log10_lr, p_h1, p_h2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lr_dist_choose_threshold
Rcpp::List cpp_lr_dist_choose_threshold(Rcpp::NumericVector log10_lr, Rcpp::NumericVector p_h1, Rcpp::NumericVector p_h2, double weight);
RcppExport SEXP _mispitools_cpp_lr_dist_choose_threshold(SEXP log10_lrSEXP, SEXP p_h1SEXP, SEXP p_h2SEXP, SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type log10_lr(log10_lrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p_h1(p_h1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p_h2(p_h2SEXP);
    Rcpp::traits::input_parameter< double >::type weight(weightSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lr_dist_choose_threshold(log10_lr, p_h1, p_h2, weight));
    return rcpp_result_gen;
END_RCPP
}
// cpp_per_marker_kl_batch
Rcpp::List cpp_per_marker_kl_batch(Rcpp::IntegerVector father, Rcpp::IntegerVector mother, int poi, Rcpp::List freqs_list, Rcpp::IntegerVector mutation_kind, Rcpp::NumericVector mutation_rate, Rcpp::NumericVector mutation_range, Rcpp::List numeric_labels_list);
RcppExport SEXP _mispitools_cpp_per_marker_kl_batch(SEXP fatherSEXP, SEXP motherSEXP, SEXP poiSEXP, SEXP freqs_listSEXP, SEXP mutation_kindSEXP, SEXP mutation_rateSEXP, SEXP mutation_rangeSEXP, SEXP numeric_labels_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type father(fatherSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type mother(motherSEXP);
    Rcpp::traits::input_parameter< int >::type poi(poiSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type freqs_list(freqs_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type mutation_kind(mutation_kindSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mutation_rate(mutation_rateSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mutation_range(mutation_rangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type numeric_labels_list(numeric_labels_listSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_per_marker_kl_batch(father, mother, poi, freqs_list, mutation_kind, mutation_rate, mutation_range, numeric_labels_list));
    return rcpp_result_gen;
END_RCPP
}
// mutation_matrix_cpp
arma::mat mutation_matrix_cpp(int K, int mutation_kind, double mutation_rate, double mutation_range, Rcpp::NumericVector numeric_labels, Rcpp::NumericVector afreq);
RcppExport SEXP _mispitools_mutation_matrix_cpp(SEXP KSEXP, SEXP mutation_kindSEXP, SEXP mutation_rateSEXP, SEXP mutation_rangeSEXP, SEXP numeric_labelsSEXP, SEXP afreqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type mutation_kind(mutation_kindSEXP);
    Rcpp::traits::input_parameter< double >::type mutation_rate(mutation_rateSEXP);
    Rcpp::traits::input_parameter< double >::type mutation_range(mutation_rangeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type numeric_labels(numeric_labelsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type afreq(afreqSEXP);
    rcpp_result_gen = Rcpp::wrap(mutation_matrix_cpp(K, mutation_kind, mutation_rate, mutation_range, numeric_labels, afreq));
    return rcpp_result_gen;
END_RCPP
}
// dawid_max_rate_cpp
double dawid_max_rate_cpp(Rcpp::NumericVector afreq, double range);
RcppExport SEXP _mispitools_dawid_max_rate_cpp(SEXP afreqSEXP, SEXP rangeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type afreq(afreqSEXP);
    Rcpp::traits::input_parameter< double >::type range(rangeSEXP);
    rcpp_result_gen = Rcpp::wrap(dawid_max_rate_cpp(afreq, range));
    return rcpp_result_gen;
END_RCPP
}
// haldane_cm_to_rho_wrap
double haldane_cm_to_rho_wrap(double cM);
RcppExport SEXP _mispitools_haldane_cm_to_rho_wrap(SEXP cMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type cM(cMSEXP);
    rcpp_result_gen = Rcpp::wrap(haldane_cm_to_rho_wrap(cM));
    return rcpp_result_gen;
END_RCPP
}
// haldane_rho_to_cm_wrap
double haldane_rho_to_cm_wrap(double rho);
RcppExport SEXP _mispitools_haldane_rho_to_cm_wrap(SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(haldane_rho_to_cm_wrap(rho));
    return rcpp_result_gen;
END_RCPP
}
// kosambi_cm_to_rho_wrap
double kosambi_cm_to_rho_wrap(double cM);
RcppExport SEXP _mispitools_kosambi_cm_to_rho_wrap(SEXP cMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type cM(cMSEXP);
    rcpp_result_gen = Rcpp::wrap(kosambi_cm_to_rho_wrap(cM));
    return rcpp_result_gen;
END_RCPP
}
// kosambi_rho_to_cm_wrap
double kosambi_rho_to_cm_wrap(double rho);
RcppExport SEXP _mispitools_kosambi_rho_to_cm_wrap(SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(kosambi_rho_to_cm_wrap(rho));
    return rcpp_result_gen;
END_RCPP
}
// cpp_linked_pair_joint
Rcpp::List cpp_linked_pair_joint(Rcpp::IntegerVector father, Rcpp::IntegerVector mother, int poi, Rcpp::NumericVector freqs_a, Rcpp::NumericVector freqs_b, double rho, int mutation_kind_a, double mutation_rate_a, double mutation_range_a, Rcpp::NumericVector numeric_labels_a, int mutation_kind_b, double mutation_rate_b, double mutation_range_b, Rcpp::NumericVector numeric_labels_b, Rcpp::IntegerVector relevant);
RcppExport SEXP _mispitools_cpp_linked_pair_joint(SEXP fatherSEXP, SEXP motherSEXP, SEXP poiSEXP, SEXP freqs_aSEXP, SEXP freqs_bSEXP, SEXP rhoSEXP, SEXP mutation_kind_aSEXP, SEXP mutation_rate_aSEXP, SEXP mutation_range_aSEXP, SEXP numeric_labels_aSEXP, SEXP mutation_kind_bSEXP, SEXP mutation_rate_bSEXP, SEXP mutation_range_bSEXP, SEXP numeric_labels_bSEXP, SEXP relevantSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type father(fatherSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type mother(motherSEXP);
    Rcpp::traits::input_parameter< int >::type poi(poiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type freqs_a(freqs_aSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type freqs_b(freqs_bSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type mutation_kind_a(mutation_kind_aSEXP);
    Rcpp::traits::input_parameter< double >::type mutation_rate_a(mutation_rate_aSEXP);
    Rcpp::traits::input_parameter< double >::type mutation_range_a(mutation_range_aSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type numeric_labels_a(numeric_labels_aSEXP);
    Rcpp::traits::input_parameter< int >::type mutation_kind_b(mutation_kind_bSEXP);
    Rcpp::traits::input_parameter< double >::type mutation_rate_b(mutation_rate_bSEXP);
    Rcpp::traits::input_parameter< double >::type mutation_range_b(mutation_range_bSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type numeric_labels_b(numeric_labels_bSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type relevant(relevantSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_linked_pair_joint(father, mother, poi, freqs_a, freqs_b, rho, mutation_kind_a, mutation_rate_a, mutation_range_a, numeric_labels_a, mutation_kind_b, mutation_rate_b, mutation_range_b, numeric_labels_b, relevant));
    return rcpp_result_gen;
END_RCPP
}
// nongenetic_cpt_cpp
Rcpp::List nongenetic_cpt_cpp(int feature_class, int n_categories, bool error_is_matrix, Rcpp::NumericVector error_matrix, double error_scalar, int observed_index, bool reference_uniform, Rcpp::NumericVector reference_freqs, double range_lo, double range_hi, Rcpp::NumericVector sample, double observed_value, int n_bins, Rcpp::NumericVector alpha, bool search_open);
RcppExport SEXP _mispitools_nongenetic_cpt_cpp(SEXP feature_classSEXP, SEXP n_categoriesSEXP, SEXP error_is_matrixSEXP, SEXP error_matrixSEXP, SEXP error_scalarSEXP, SEXP observed_indexSEXP, SEXP reference_uniformSEXP, SEXP reference_freqsSEXP, SEXP range_loSEXP, SEXP range_hiSEXP, SEXP sampleSEXP, SEXP observed_valueSEXP, SEXP n_binsSEXP, SEXP alphaSEXP, SEXP search_openSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type feature_class(feature_classSEXP);
    Rcpp::traits::input_parameter< int >::type n_categories(n_categoriesSEXP);
    Rcpp::traits::input_parameter< bool >::type error_is_matrix(error_is_matrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type error_matrix(error_matrixSEXP);
    Rcpp::traits::input_parameter< double >::type error_scalar(error_scalarSEXP);
    Rcpp::traits::input_parameter< int >::type observed_index(observed_indexSEXP);
    Rcpp::traits::input_parameter< bool >::type reference_uniform(reference_uniformSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type reference_freqs(reference_freqsSEXP);
    Rcpp::traits::input_parameter< double >::type range_lo(range_loSEXP);
    Rcpp::traits::input_parameter< double >::type range_hi(range_hiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< double >::type observed_value(observed_valueSEXP);
    Rcpp::traits::input_parameter< int >::type n_bins(n_binsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type search_open(search_openSEXP);
    rcpp_result_gen = Rcpp::wrap(nongenetic_cpt_cpp(feature_class, n_categories, error_is_matrix, error_matrix, error_scalar, observed_index, reference_uniform, reference_freqs, range_lo, range_hi, sample, observed_value, n_bins, alpha, search_open));
    return rcpp_result_gen;
END_RCPP
}
// nongenetic_per_feature_kl_cpp
Rcpp::List nongenetic_per_feature_kl_cpp(int feature_class, int n_categories, bool error_is_matrix, Rcpp::NumericVector error_matrix, double error_scalar, int observed_index, bool reference_uniform, Rcpp::NumericVector reference_freqs, double range_lo, double range_hi, Rcpp::NumericVector sample, double observed_value, int n_bins, Rcpp::NumericVector alpha, bool search_open);
RcppExport SEXP _mispitools_nongenetic_per_feature_kl_cpp(SEXP feature_classSEXP, SEXP n_categoriesSEXP, SEXP error_is_matrixSEXP, SEXP error_matrixSEXP, SEXP error_scalarSEXP, SEXP observed_indexSEXP, SEXP reference_uniformSEXP, SEXP reference_freqsSEXP, SEXP range_loSEXP, SEXP range_hiSEXP, SEXP sampleSEXP, SEXP observed_valueSEXP, SEXP n_binsSEXP, SEXP alphaSEXP, SEXP search_openSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type feature_class(feature_classSEXP);
    Rcpp::traits::input_parameter< int >::type n_categories(n_categoriesSEXP);
    Rcpp::traits::input_parameter< bool >::type error_is_matrix(error_is_matrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type error_matrix(error_matrixSEXP);
    Rcpp::traits::input_parameter< double >::type error_scalar(error_scalarSEXP);
    Rcpp::traits::input_parameter< int >::type observed_index(observed_indexSEXP);
    Rcpp::traits::input_parameter< bool >::type reference_uniform(reference_uniformSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type reference_freqs(reference_freqsSEXP);
    Rcpp::traits::input_parameter< double >::type range_lo(range_loSEXP);
    Rcpp::traits::input_parameter< double >::type range_hi(range_hiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< double >::type observed_value(observed_valueSEXP);
    Rcpp::traits::input_parameter< int >::type n_bins(n_binsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type search_open(search_openSEXP);
    rcpp_result_gen = Rcpp::wrap(nongenetic_per_feature_kl_cpp(feature_class, n_categories, error_is_matrix, error_matrix, error_scalar, observed_index, reference_uniform, reference_freqs, range_lo, range_hi, sample, observed_value, n_bins, alpha, search_open));
    return rcpp_result_gen;
END_RCPP
}
// nongenetic_per_feature_lr_dist_cpp
Rcpp::List nongenetic_per_feature_lr_dist_cpp(int feature_class, int n_categories, bool error_is_matrix, Rcpp::NumericVector error_matrix, double error_scalar, int observed_index, bool reference_uniform, Rcpp::NumericVector reference_freqs, double range_lo, double range_hi, Rcpp::NumericVector sample, double observed_value, int n_bins, Rcpp::NumericVector alpha, bool search_open, bool aggregate);
RcppExport SEXP _mispitools_nongenetic_per_feature_lr_dist_cpp(SEXP feature_classSEXP, SEXP n_categoriesSEXP, SEXP error_is_matrixSEXP, SEXP error_matrixSEXP, SEXP error_scalarSEXP, SEXP observed_indexSEXP, SEXP reference_uniformSEXP, SEXP reference_freqsSEXP, SEXP range_loSEXP, SEXP range_hiSEXP, SEXP sampleSEXP, SEXP observed_valueSEXP, SEXP n_binsSEXP, SEXP alphaSEXP, SEXP search_openSEXP, SEXP aggregateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type feature_class(feature_classSEXP);
    Rcpp::traits::input_parameter< int >::type n_categories(n_categoriesSEXP);
    Rcpp::traits::input_parameter< bool >::type error_is_matrix(error_is_matrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type error_matrix(error_matrixSEXP);
    Rcpp::traits::input_parameter< double >::type error_scalar(error_scalarSEXP);
    Rcpp::traits::input_parameter< int >::type observed_index(observed_indexSEXP);
    Rcpp::traits::input_parameter< bool >::type reference_uniform(reference_uniformSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type reference_freqs(reference_freqsSEXP);
    Rcpp::traits::input_parameter< double >::type range_lo(range_loSEXP);
    Rcpp::traits::input_parameter< double >::type range_hi(range_hiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< double >::type observed_value(observed_valueSEXP);
    Rcpp::traits::input_parameter< int >::type n_bins(n_binsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type search_open(search_openSEXP);
    Rcpp::traits::input_parameter< bool >::type aggregate(aggregateSEXP);
    rcpp_result_gen = Rcpp::wrap(nongenetic_per_feature_lr_dist_cpp(feature_class, n_categories, error_is_matrix, error_matrix, error_scalar, observed_index, reference_uniform, reference_freqs, range_lo, range_hi, sample, observed_value, n_bins, alpha, search_open, aggregate));
    return rcpp_result_gen;
END_RCPP
}
// cpp_openmp_info
Rcpp::List cpp_openmp_info(int n_threads);
RcppExport SEXP _mispitools_cpp_openmp_info(SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_openmp_info(n_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mispitools_cpp_pedigree_placeholder", (DL_FUNC) &_mispitools_cpp_pedigree_placeholder, 1},
    {"_mispitools_cpp_marker_placeholder", (DL_FUNC) &_mispitools_cpp_marker_placeholder, 1},
    {"_mispitools_cpp_mutation_models_placeholder", (DL_FUNC) &_mispitools_cpp_mutation_models_placeholder, 1},
    {"_mispitools_cpp_cpt_engine_placeholder", (DL_FUNC) &_mispitools_cpp_cpt_engine_placeholder, 1},
    {"_mispitools_cpp_kl_engine_placeholder", (DL_FUNC) &_mispitools_cpp_kl_engine_placeholder, 1},
    {"_mispitools_cpp_lr_dist_placeholder", (DL_FUNC) &_mispitools_cpp_lr_dist_placeholder, 1},
    {"_mispitools_cpp_nongenetic_lr_placeholder", (DL_FUNC) &_mispitools_cpp_nongenetic_lr_placeholder, 1},
    {"_mispitools_cpp_evidence_combine_placeholder", (DL_FUNC) &_mispitools_cpp_evidence_combine_placeholder, 1},
    {"_mispitools_cpp_concentration_placeholder", (DL_FUNC) &_mispitools_cpp_concentration_placeholder, 1},
    {"_mispitools_cpp_decision_placeholder", (DL_FUNC) &_mispitools_cpp_decision_placeholder, 1},
    {"_mispitools_cpp_linkage_placeholder", (DL_FUNC) &_mispitools_cpp_linkage_placeholder, 1},
    {"_mispitools_cpt_marker_joint_cpp", (DL_FUNC) &_mispitools_cpt_marker_joint_cpp, 11},
    {"_mispitools_cpp_per_marker_kl", (DL_FUNC) &_mispitools_cpp_per_marker_kl, 2},
    {"_mispitools_cpp_per_marker_lr_dist", (DL_FUNC) &_mispitools_cpp_per_marker_lr_dist, 3},
    {"_mispitools_cpp_lr_dist_compose", (DL_FUNC) &_mispitools_cpp_lr_dist_compose, 4},
    {"_mispitools_cpp_evidence_combine", (DL_FUNC) &_mispitools_cpp_evidence_combine, 3},
    {"_mispitools_cpp_lr_dist_summary", (DL_FUNC) &_mispitools_cpp_lr_dist_summary, 3},
    {"_mispitools_cpp_lr_dist_quantile", (DL_FUNC) &_mispitools_cpp_lr_dist_quantile, 5},
    {"_mispitools_cpp_lr_dist_decision_rates", (DL_FUNC) &_mispitools_cpp_lr_dist_decision_rates, 4},
    {"_mispitools_cpp_lr_dist_roc", (DL_FUNC) &_mispitools_cpp_lr_dist_roc, 3},
    {"_mispitools_cpp_lr_dist_choose_threshold", (DL_FUNC) &_mispitools_cpp_lr_dist_choose_threshold, 4},
    {"_mispitools_cpp_per_marker_kl_batch", (DL_FUNC) &_mispitools_cpp_per_marker_kl_batch, 8},
    {"_mispitools_mutation_matrix_cpp", (DL_FUNC) &_mispitools_mutation_matrix_cpp, 6},
    {"_mispitools_dawid_max_rate_cpp", (DL_FUNC) &_mispitools_dawid_max_rate_cpp, 2},
    {"_mispitools_haldane_cm_to_rho_wrap", (DL_FUNC) &_mispitools_haldane_cm_to_rho_wrap, 1},
    {"_mispitools_haldane_rho_to_cm_wrap", (DL_FUNC) &_mispitools_haldane_rho_to_cm_wrap, 1},
    {"_mispitools_kosambi_cm_to_rho_wrap", (DL_FUNC) &_mispitools_kosambi_cm_to_rho_wrap, 1},
    {"_mispitools_kosambi_rho_to_cm_wrap", (DL_FUNC) &_mispitools_kosambi_rho_to_cm_wrap, 1},
    {"_mispitools_cpp_linked_pair_joint", (DL_FUNC) &_mispitools_cpp_linked_pair_joint, 15},
    {"_mispitools_nongenetic_cpt_cpp", (DL_FUNC) &_mispitools_nongenetic_cpt_cpp, 15},
    {"_mispitools_nongenetic_per_feature_kl_cpp", (DL_FUNC) &_mispitools_nongenetic_per_feature_kl_cpp, 15},
    {"_mispitools_nongenetic_per_feature_lr_dist_cpp", (DL_FUNC) &_mispitools_nongenetic_per_feature_lr_dist_cpp, 16},
    {"_mispitools_cpp_openmp_info", (DL_FUNC) &_mispitools_cpp_openmp_info, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_mispitools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
