// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_pedigree_placeholder
int cpp_pedigree_placeholder(int x);
RcppExport SEXP _mispitools_cpp_pedigree_placeholder(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pedigree_placeholder(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_marker_placeholder
int cpp_marker_placeholder(int x);
RcppExport SEXP _mispitools_cpp_marker_placeholder(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_marker_placeholder(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_mutation_models_placeholder
int cpp_mutation_models_placeholder(int x);
RcppExport SEXP _mispitools_cpp_mutation_models_placeholder(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_mutation_models_placeholder(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cpt_engine_placeholder
int cpp_cpt_engine_placeholder(int x);
RcppExport SEXP _mispitools_cpp_cpt_engine_placeholder(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cpt_engine_placeholder(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_kl_engine_placeholder
int cpp_kl_engine_placeholder(int x);
RcppExport SEXP _mispitools_cpp_kl_engine_placeholder(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_kl_engine_placeholder(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lr_dist_placeholder
int cpp_lr_dist_placeholder(int x);
RcppExport SEXP _mispitools_cpp_lr_dist_placeholder(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lr_dist_placeholder(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_nongenetic_lr_placeholder
int cpp_nongenetic_lr_placeholder(int x);
RcppExport SEXP _mispitools_cpp_nongenetic_lr_placeholder(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_nongenetic_lr_placeholder(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_evidence_combine_placeholder
int cpp_evidence_combine_placeholder(int x);
RcppExport SEXP _mispitools_cpp_evidence_combine_placeholder(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_evidence_combine_placeholder(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_concentration_placeholder
int cpp_concentration_placeholder(int x);
RcppExport SEXP _mispitools_cpp_concentration_placeholder(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_concentration_placeholder(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_decision_placeholder
int cpp_decision_placeholder(int x);
RcppExport SEXP _mispitools_cpp_decision_placeholder(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_decision_placeholder(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_linkage_placeholder
int cpp_linkage_placeholder(int x);
RcppExport SEXP _mispitools_cpp_linkage_placeholder(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_linkage_placeholder(x));
    return rcpp_result_gen;
END_RCPP
}
// cpt_marker_joint_cpp
Rcpp::List cpt_marker_joint_cpp(Rcpp::IntegerVector father, Rcpp::IntegerVector mother, int poi, Rcpp::NumericVector freqs, int mutation_kind, double mutation_rate, double mutation_range, double mutation_rate2, double mutation_bias, Rcpp::NumericVector numeric_labels);
RcppExport SEXP _mispitools_cpt_marker_joint_cpp(SEXP fatherSEXP, SEXP motherSEXP, SEXP poiSEXP, SEXP freqsSEXP, SEXP mutation_kindSEXP, SEXP mutation_rateSEXP, SEXP mutation_rangeSEXP, SEXP mutation_rate2SEXP, SEXP mutation_biasSEXP, SEXP numeric_labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type father(fatherSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type mother(motherSEXP);
    Rcpp::traits::input_parameter< int >::type poi(poiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type freqs(freqsSEXP);
    Rcpp::traits::input_parameter< int >::type mutation_kind(mutation_kindSEXP);
    Rcpp::traits::input_parameter< double >::type mutation_rate(mutation_rateSEXP);
    Rcpp::traits::input_parameter< double >::type mutation_range(mutation_rangeSEXP);
    Rcpp::traits::input_parameter< double >::type mutation_rate2(mutation_rate2SEXP);
    Rcpp::traits::input_parameter< double >::type mutation_bias(mutation_biasSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type numeric_labels(numeric_labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpt_marker_joint_cpp(father, mother, poi, freqs, mutation_kind, mutation_rate, mutation_range, mutation_rate2, mutation_bias, numeric_labels));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mispitools_cpp_pedigree_placeholder", (DL_FUNC) &_mispitools_cpp_pedigree_placeholder, 1},
    {"_mispitools_cpp_marker_placeholder", (DL_FUNC) &_mispitools_cpp_marker_placeholder, 1},
    {"_mispitools_cpp_mutation_models_placeholder", (DL_FUNC) &_mispitools_cpp_mutation_models_placeholder, 1},
    {"_mispitools_cpp_cpt_engine_placeholder", (DL_FUNC) &_mispitools_cpp_cpt_engine_placeholder, 1},
    {"_mispitools_cpp_kl_engine_placeholder", (DL_FUNC) &_mispitools_cpp_kl_engine_placeholder, 1},
    {"_mispitools_cpp_lr_dist_placeholder", (DL_FUNC) &_mispitools_cpp_lr_dist_placeholder, 1},
    {"_mispitools_cpp_nongenetic_lr_placeholder", (DL_FUNC) &_mispitools_cpp_nongenetic_lr_placeholder, 1},
    {"_mispitools_cpp_evidence_combine_placeholder", (DL_FUNC) &_mispitools_cpp_evidence_combine_placeholder, 1},
    {"_mispitools_cpp_concentration_placeholder", (DL_FUNC) &_mispitools_cpp_concentration_placeholder, 1},
    {"_mispitools_cpp_decision_placeholder", (DL_FUNC) &_mispitools_cpp_decision_placeholder, 1},
    {"_mispitools_cpp_linkage_placeholder", (DL_FUNC) &_mispitools_cpp_linkage_placeholder, 1},
    {"_mispitools_cpt_marker_joint_cpp", (DL_FUNC) &_mispitools_cpt_marker_joint_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_mispitools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
