# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_pedigree_placeholder <- function(x) {
    .Call(`_mispitools_cpp_pedigree_placeholder`, x)
}

cpp_marker_placeholder <- function(x) {
    .Call(`_mispitools_cpp_marker_placeholder`, x)
}

cpp_mutation_models_placeholder <- function(x) {
    .Call(`_mispitools_cpp_mutation_models_placeholder`, x)
}

cpp_cpt_engine_placeholder <- function(x) {
    .Call(`_mispitools_cpp_cpt_engine_placeholder`, x)
}

cpp_kl_engine_placeholder <- function(x) {
    .Call(`_mispitools_cpp_kl_engine_placeholder`, x)
}

cpp_lr_dist_placeholder <- function(x) {
    .Call(`_mispitools_cpp_lr_dist_placeholder`, x)
}

cpp_nongenetic_lr_placeholder <- function(x) {
    .Call(`_mispitools_cpp_nongenetic_lr_placeholder`, x)
}

cpp_evidence_combine_placeholder <- function(x) {
    .Call(`_mispitools_cpp_evidence_combine_placeholder`, x)
}

cpp_concentration_placeholder <- function(x) {
    .Call(`_mispitools_cpp_concentration_placeholder`, x)
}

cpp_decision_placeholder <- function(x) {
    .Call(`_mispitools_cpp_decision_placeholder`, x)
}

cpp_linkage_placeholder <- function(x) {
    .Call(`_mispitools_cpp_linkage_placeholder`, x)
}

cpt_marker_joint_cpp <- function(father, mother, poi, freqs, mutation_kind = 0L, mutation_rate = 0.0, mutation_range = 0.0, mutation_rate2 = 0.0, mutation_bias = 0.5, numeric_labels = as.numeric( c()), relevant = as.integer( c())) {
    .Call(`_mispitools_cpt_marker_joint_cpp`, father, mother, poi, freqs, mutation_kind, mutation_rate, mutation_range, mutation_rate2, mutation_bias, numeric_labels, relevant)
}

cpp_per_marker_kl <- function(p_h1, p_h2) {
    .Call(`_mispitools_cpp_per_marker_kl`, p_h1, p_h2)
}

cpp_per_marker_lr_dist <- function(p_h1, p_h2, aggregate = TRUE) {
    .Call(`_mispitools_cpp_per_marker_lr_dist`, p_h1, p_h2, aggregate)
}

cpp_lr_dist_compose <- function(dists, method = "exact", merge_tol = 0.0, grid_points = 512L) {
    .Call(`_mispitools_cpp_lr_dist_compose`, dists, method, merge_tol, grid_points)
}

cpp_evidence_combine <- function(dists, mode = "independent", transition = NULL) {
    .Call(`_mispitools_cpp_evidence_combine`, dists, mode, transition)
}

cpp_lr_dist_summary <- function(log10_lr, p_h1, p_h2) {
    .Call(`_mispitools_cpp_lr_dist_summary`, log10_lr, p_h1, p_h2)
}

cpp_lr_dist_quantile <- function(log10_lr, p_h1, p_h2, probs, under_h1 = TRUE) {
    .Call(`_mispitools_cpp_lr_dist_quantile`, log10_lr, p_h1, p_h2, probs, under_h1)
}

cpp_lr_dist_decision_rates <- function(log10_lr, p_h1, p_h2, threshold) {
    .Call(`_mispitools_cpp_lr_dist_decision_rates`, log10_lr, p_h1, p_h2, threshold)
}

cpp_lr_dist_roc <- function(log10_lr, p_h1, p_h2) {
    .Call(`_mispitools_cpp_lr_dist_roc`, log10_lr, p_h1, p_h2)
}

cpp_lr_dist_choose_threshold <- function(log10_lr, p_h1, p_h2, weight = 10.0) {
    .Call(`_mispitools_cpp_lr_dist_choose_threshold`, log10_lr, p_h1, p_h2, weight)
}

cpp_per_marker_kl_batch <- function(father, mother, poi, freqs_list, mutation_kind, mutation_rate, mutation_range, numeric_labels_list) {
    .Call(`_mispitools_cpp_per_marker_kl_batch`, father, mother, poi, freqs_list, mutation_kind, mutation_rate, mutation_range, numeric_labels_list)
}

mutation_matrix_cpp <- function(K, mutation_kind = 0L, mutation_rate = 0.0, mutation_range = 0.0, numeric_labels = as.numeric( c()), afreq = as.numeric( c())) {
    .Call(`_mispitools_mutation_matrix_cpp`, K, mutation_kind, mutation_rate, mutation_range, numeric_labels, afreq)
}

dawid_max_rate_cpp <- function(afreq, range) {
    .Call(`_mispitools_dawid_max_rate_cpp`, afreq, range)
}

haldane_cm_to_rho_wrap <- function(cM) {
    .Call(`_mispitools_haldane_cm_to_rho_wrap`, cM)
}

haldane_rho_to_cm_wrap <- function(rho) {
    .Call(`_mispitools_haldane_rho_to_cm_wrap`, rho)
}

kosambi_cm_to_rho_wrap <- function(cM) {
    .Call(`_mispitools_kosambi_cm_to_rho_wrap`, cM)
}

kosambi_rho_to_cm_wrap <- function(rho) {
    .Call(`_mispitools_kosambi_rho_to_cm_wrap`, rho)
}

cpp_linked_pair_joint <- function(father, mother, poi, freqs_a, freqs_b, rho, mutation_kind_a = 0L, mutation_rate_a = 0.0, mutation_range_a = 0.0, numeric_labels_a = as.numeric( c()), mutation_kind_b = 0L, mutation_rate_b = 0.0, mutation_range_b = 0.0, numeric_labels_b = as.numeric( c()), relevant = as.integer( c())) {
    .Call(`_mispitools_cpp_linked_pair_joint`, father, mother, poi, freqs_a, freqs_b, rho, mutation_kind_a, mutation_rate_a, mutation_range_a, numeric_labels_a, mutation_kind_b, mutation_rate_b, mutation_range_b, numeric_labels_b, relevant)
}

nongenetic_cpt_cpp <- function(feature_class, n_categories, error_is_matrix, error_matrix, error_scalar, observed_index, reference_uniform, reference_freqs, range_lo, range_hi, sample, observed_value, n_bins, alpha, search_open) {
    .Call(`_mispitools_nongenetic_cpt_cpp`, feature_class, n_categories, error_is_matrix, error_matrix, error_scalar, observed_index, reference_uniform, reference_freqs, range_lo, range_hi, sample, observed_value, n_bins, alpha, search_open)
}

nongenetic_per_feature_kl_cpp <- function(feature_class, n_categories, error_is_matrix, error_matrix, error_scalar, observed_index, reference_uniform, reference_freqs, range_lo, range_hi, sample, observed_value, n_bins, alpha, search_open) {
    .Call(`_mispitools_nongenetic_per_feature_kl_cpp`, feature_class, n_categories, error_is_matrix, error_matrix, error_scalar, observed_index, reference_uniform, reference_freqs, range_lo, range_hi, sample, observed_value, n_bins, alpha, search_open)
}

nongenetic_per_feature_lr_dist_cpp <- function(feature_class, n_categories, error_is_matrix, error_matrix, error_scalar, observed_index, reference_uniform, reference_freqs, range_lo, range_hi, sample, observed_value, n_bins, alpha, search_open, aggregate = TRUE) {
    .Call(`_mispitools_nongenetic_per_feature_lr_dist_cpp`, feature_class, n_categories, error_is_matrix, error_matrix, error_scalar, observed_index, reference_uniform, reference_freqs, range_lo, range_hi, sample, observed_value, n_bins, alpha, search_open, aggregate)
}

cpp_openmp_info <- function(n_threads = 0L) {
    .Call(`_mispitools_cpp_openmp_info`, n_threads)
}

