# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_pedigree_placeholder <- function(x) {
    .Call(`_mispitools_cpp_pedigree_placeholder`, x)
}

cpp_marker_placeholder <- function(x) {
    .Call(`_mispitools_cpp_marker_placeholder`, x)
}

cpp_mutation_models_placeholder <- function(x) {
    .Call(`_mispitools_cpp_mutation_models_placeholder`, x)
}

cpp_cpt_engine_placeholder <- function(x) {
    .Call(`_mispitools_cpp_cpt_engine_placeholder`, x)
}

cpp_kl_engine_placeholder <- function(x) {
    .Call(`_mispitools_cpp_kl_engine_placeholder`, x)
}

cpp_lr_dist_placeholder <- function(x) {
    .Call(`_mispitools_cpp_lr_dist_placeholder`, x)
}

cpp_nongenetic_lr_placeholder <- function(x) {
    .Call(`_mispitools_cpp_nongenetic_lr_placeholder`, x)
}

cpp_evidence_combine_placeholder <- function(x) {
    .Call(`_mispitools_cpp_evidence_combine_placeholder`, x)
}

cpp_concentration_placeholder <- function(x) {
    .Call(`_mispitools_cpp_concentration_placeholder`, x)
}

cpp_decision_placeholder <- function(x) {
    .Call(`_mispitools_cpp_decision_placeholder`, x)
}

cpp_linkage_placeholder <- function(x) {
    .Call(`_mispitools_cpp_linkage_placeholder`, x)
}

cpt_marker_joint_cpp <- function(father, mother, poi, freqs, mutation_kind = 0L, mutation_rate = 0.0, mutation_range = 0.0, mutation_rate2 = 0.0, mutation_bias = 0.5, numeric_labels = as.numeric( c())) {
    .Call(`_mispitools_cpt_marker_joint_cpp`, father, mother, poi, freqs, mutation_kind, mutation_rate, mutation_range, mutation_rate2, mutation_bias, numeric_labels)
}

